version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  gcp:
    class: google.cloud.logging_v2.handlers.structured_log.StructuredLogHandler

  rich:
    class: rich.logging.RichHandler

loggers:
  kedro:
    level: INFO

  forecasting_model:
    level: INFO

root:
  handlers: [rich]
