name: Deploy infrastructure

on:
  workflow_dispatch:
  push:
    paths:
    - 'infrastructure/modules/data-mock/python/**'

jobs:
  deploy-infra:
    name: 'Deploy infrastructure'
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'infrastructure'
    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: 'true'
        credentials_json: '${{ secrets.GOOGLE_CLOUD }}'
    
    - name: 'Set up Terraform'
      uses: 'hashicorp/setup-terraform@v2'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Initialize Terraform'
      run: 'terraform init -input=false'

    - name: 'Plan infrastructure'
      run: 'terraform plan -out=tfplan -input=false'

    - name: Apply infrastructure
      run: 'terraform apply -input=false tfplan'

  deploy-functions:
    name: 'Deploy Cloud Functions' 
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CLOUD }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Deploy Cloud Function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'data-mock-568de2'
        description: 'Function producing mocked data'
        runtime: 'python310'
        entry_point: 'produce'
        memory_mb: 1024
        region: 'europe-west1'
        env_vars: 'TOPIC=projects/mlops-383318/topics/order-book-568de2,COUNT=100'
        labels: 'owner=matkob,purpose=mlops-demo,type=mock'
        source_dir: 'infrastructure/modules/data-mock/python'
        timeout: 120
        max_instances: 1
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: 'projects/mlops-383318/topics/data-mock-trigger-568de2'
        build_environment_variables: 'GOOGLE_FUNCTION_SOURCE=mock_data.py'
